# Generated by Django 4.2.20 on 2025-03-08 23:07

from django.db import migrations
from messangerApp.management.commands.data_base_mock_fill import Command

def generate_data(apps, schema_editor):
    Command().handle()

# Dangerous to use !!!
def ungenerate_data(apps, schema_editor):
    Command().unhandle()

class Migration(migrations.Migration):

    dependencies = [
        ('messangerApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_data, ungenerate_data),
    ]
