services:
  messanger:
    build:
      dockerfile: Dockerfile_messanger
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env_compose
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "5433:5432"
    volumes:
      - pg_messanger_data:/var/lib/postgresql/data
volumes:
  pg_messanger_data: